ALTER TABLE san_fact_programa_cab
ADD COLUMN categoria VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN tipoCDP VARCHAR(20) NULL DEFAULT NULL,
ADD COLUMN esEspecial TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN modoEspecial VARCHAR(20) NULL DEFAULT NULL;

ALTER TABLE san_fact_programa_det
ADD COLUMN fechas TEXT NULL DEFAULT NULL AFTER cantidadPorGalpon,
ADD COLUMN intervaloMeses INT NULL DEFAULT NULL AFTER fechas,
ADD COLUMN diaDelMes INT NULL DEFAULT NULL AFTER intervaloMeses,
ADD COLUMN tolerancia INT NULL DEFAULT NULL AFTER diaDelMes;

ALTER TABLE san_fact_cronograma
ADD COLUMN observaciones VARCHAR(500) NULL DEFAULT NULL,
ADD COLUMN tolerancia INT NULL DEFAULT NULL;
